### PR TITLE
[pom] Replaces the maven property with project property.

### PR DESCRIPTION
**Pull request by LinMingQiang**
### Purpose

In my production environment I get compilation errors : 
```
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.13.0:check (spotless-check) on project paimon-parent: Execution spotless-check of goal com.diffplug.spotless:spotless-maven-plugin:2.13.0:check failed: Unable to locate file with path: ${maven.multiModuleProjectDirectory}/.scalafmt.conf: Could not find resource '${maven.multiModuleProjectDirectory}/.scalafmt.conf'. -> [Help 1]
```

Parameter ${maven.multiModuleProjectDirectory}  is not a recommended parameter. Use ${project.basedir} instead of it. 

References ：
https://stackoverflow.com/questions/29778262/what-is-maven-multimoduleprojectdirectory-used-for

https://github.com/apache/iotdb/pull/12982

Linked issue: close #xxx

### CODE REVIEW

**Comment by Zouxxyy** [comment]
The reason why introduce `${maven.multiModuleProjectDirectory} `  was that some users like to cd sub-module and then execute mvn, this work well with maven 3.3.1+. ${project.basedir} may not solve this.

A better way is to replace it with `${project.rootDirectory}` after maven 4.0.0, see MNG-7038 (The version is too high, so this solution is not considered)

**Comment by LinMingQiang** [comment]
In this scenario, we should recommend using ```mvn -pl ```. But in many cases parameter ```${maven.multiModuleProjectDirectory}``` would not be set , which causes the entire project to fail to compile. I think production stability is more important. WDYT.

**Comment by Zouxxyy** [comment]
> In this scenario, we should recommend using mvn -pl 

Agree, https://github.com/apache/paimon/pull/3063 is just added for users who don't know how to use it (see my comment in it). Actually it can be reverted.

**Comment by Zouxxyy** [comment]
> But in many cases parameter ${maven.multiModuleProjectDirectory} would not be set 

Can you give more details, is maven 3.3.1- or a very high version?

**Comment by LinMingQiang** [comment]
> > But in many cases parameter ${maven.multiModuleProjectDirectory} would not be set
> 
> Can you give more details, is maven 3.3.1- or a very high version?

My case is maven 3.2.5, this forced me to modify my pom.

**Comment by LinMingQiang** [comment]
I think production stability is more important than this feature https://github.com/apache/paimon/pull/3063, because production failure has already happened to me , WDYT.

**Comment by LinMingQiang** [comment]
Revert https://github.com/apache/paimon/pull/3063

**Comment by JingsongLi** [comment]
What are the current issue? 

Why is your compilation errors? @LinMingQiang (In my env, it is fine)

**Comment by JingsongLi** [comment]
I think better choice is upgrade your maven version.
